const projects = [
  {
    title: "Toki Pona Sitelen",
    subtitle: "HTML CSS Javascript",
    site: "https://realjhoo.com/projects/toki-pona-sitelen/",
    git: "https://github.com/realjhoo/toki-pona",
    description:
      "Using the linja-pona font, this app provides practice for identifying Toki Pona words and sitelen pona.",
    thumbnail: "img/toki-pona.png",
    altThumbnail: "Toki Pona Practice Thumbnail",
  },
  {
    title: "Potential",
    subtitle: "Chrome Extension",
    site: "https://realjhoo.com/projects/potential/",
    git: "https://github.com/realjhoo/potential-chrome-extension",
    description:
      "Based on Momentum, this Chrome Extension displays local weather, moon phase and date & time, as well as selected holidays and inspirational messages.",
    thumbnail: "img/project-11.png",
    altThumbnail: "Potential Thumbnail",
  },
  {
    title: "Keep Cat Fed",
    subtitle: "Wordpress WP Themes",
    site: "https://keepcatfed.com",
    git: "https://realjhoo.com/wp-project",
    description:
      "This affiliate WordPress site uses custom themes to promote Amazon sales",
    thumbnail: "img/keepcatfed.png",
    altThumbnail: "Keep Cat Fed Thumbnail",
  },
  {
    title: "The Torque Hub",
    subtitle: "Wordpress WP Themes",
    site: "https://thetorquehub.com",
    git: "https://realjhoo.com/wp-project",
    description:
      "This WordPress site uses custom themes to promote niche Amazon sales",
    thumbnail: "img/thetorquehub.png",
    altThumbnail: "Torque Hub Thumbnail",
  },
  {
    title: "Random Quotes",
    subtitle: "HTML CSS Javascript",
    site: "https://realjhoo.com/projects/hoo-project-10",
    git: "https://github.com/realjhoo/fullstack-project-1",
    description: "Uses Javascript to generate and display random quotes",
    thumbnail: "img/project-10.png",
    altThumbnail: "Project 10 Thumbnail",
  },
  {
    title: "API Employee Directory",
    subtitle: "CSS Fetch JSON Javascript",
    site: "https://realjhoo.com/projects/fs-project-8",
    git: "https://github.com/realjhoo/fullstack-project-5",
    description: "Uses fetch to retrieve random users and allows live search",
    thumbnail: "img/project-8.png",
    altThumbnail: "Project 8 Thumbnail",
  },
  {
    title: "Web App Dashboard",
    subtitle: "HTML CSS Grid Javascript",
    site: "https://realjhoo.com/projects/treehouse-project-7",
    git: "https://github.com/realjhoo/treehouse-project-7",
    description:
      "A mockup of a web app dashboard using chart.js, featuring local storage capabilities",
    thumbnail: "img/project-7.png",
    altThumbnail: "Project 7 Thumbnail",
  },
  {
    title: "Javascript Word Game",
    subtitle: "HTML CSS Javascript",
    site: "https://realjhoo.com/projects/treehouse-project-6",
    git: "https://github.com/realjhoo/treehouse-project-6",
    description: "A hangman-style word game created using CSS and Javascript",
    thumbnail: "img/project-6.png",
    altThumbnail: "Project 6 Thumbnail",
  },
  {
    title: "Photo Gallery",
    subtitle: "HTML CSS JQuery",
    site: "https://realjhoo.com/projects/treehouse-project-5",
    git: "https://github.com/realjhoo/treehouse-project-5",
    description:
      "An interactive live search photo gallery built using Javascript/Jquery",
    thumbnail: "img/project-5.png",
    altThumbnail: "Project 5 Thumbnail",
  },
  {
    title: "Web Style Guide",
    subtitle: "HTML CSS SASS",
    site: "https://realjhoo.com/projects/treehouse-project-4",
    git: "https://github.com/realjhoo/treehouse-project-4",
    description:
      "A web style guide built with SASS, using partials, extends, variables and mixins.",
    thumbnail: "img/project-4.png",
    altThumbnail: "Project 4 Thumbnail",
  },
  {
    title: "Registration Form",
    subtitle: "HTML CSS Javascript",
    site: "https://realjhoo.com/projects/fullstack-project-3",
    git: "https://github.com/realjhoo/fullstack-project-3",
    description: "An HTML5 form built using data validation.",
    thumbnail: "img/project-3.png",
    altThumbnail: "Project 3 Thumbnail",
  },
];
